### PR TITLE
Added dependency to fix yarn pnp warning

### LINKED ISSUE #49: Missing dependency when using this package
image
Using this package with stylelint and yarn pnp, throws this error

### PR DESCRIPTION
**Pull request by bryanjtc**
Fixes #49 
Added postcss-value-parser as dependency

### CODE REVIEW

**Comment by bryanjtc** [comment]
@kristerkari Can you check this?

**Comment by kristerkari** [comment]
Yeah, it think that it was at least previously included in the `stylelint` package.

**Comment by bryanjtc** [comment]
@kristerkari Any update on when this is going to be merged?

**Comment by kristerkari** [comment]
Sorry, totally forgot about this!

**Comment by bryanjtc** [comment]
@kristerkari Can you also release a new version on npm?

**Comment by kristerkari** [comment]
yes, just need to wait for the CI to run first

**Pull request merged**
